version: '3.8'

services:
  rabbitmq-svc:
    hostname: rabbitmq-srv
    image: rabbitmq:3-management
    container_name: rabbitmq-ctr
    ports:
      - 15672:15672
    environment:
      - RABBITMQ_DEFAULT_USER=dev_user
      - RABBITMQ_DEFAULT_PASS=pa55w0rd
    healthcheck:
      test: rabbitmq-diagnostics -q status
      interval: 10s
      timeout: 10s
      retries: 10

  sender-svc:
    container_name: sender-ctr
    image: rabbitmq-tutorial1-python-sender:latest
    environment:
      - RABBITMQ_USER=dev_user
      - RABBITMQ_PASSWORD=pa55w0rd
    depends_on:
      rabbitmq-svc:
        condition: service_healthy

  receiver-svc:
    container_name: receiver-ctr
    image: rabbitmq-tutorial1-python-receiver:latest
    environment:
      - RABBITMQ_USER=dev_user
      - RABBITMQ_PASSWORD=pa55w0rd
    depends_on:
      rabbitmq-svc:
        condition: service_healthy

