version: '3.8'

services:
  rabbitmq-svc:
    hostname: rabbitmq-srv
    image: rabbitmq:3-management
    container_name: rabbitmq-ctr
    ports:
      - 15672:15672
    environment:
      - RABBITMQ_DEFAULT_USER=dev_user
      - RABBITMQ_DEFAULT_PASS=pa55w0rd
    healthcheck:
      test: rabbitmq-diagnostics -q status
      interval: 10s
      timeout: 10s
      retries: 10
    volumes:
      - ./rabbitmq/data/:/var/lib/rabbitmq/mnesia/
      - ./rabbitmq/log/:/var/log/rabbitmq/
    networks:
      - rabbitmq-net

  producer-svc:
    container_name: producer-ctr
    image: rabbitmq-work-queues-python-producer:latest
    environment:
      - RABBITMQ_USER=dev_user
      - RABBITMQ_PASSWORD=pa55w0rd
      - FROM_TASK_ID=150
      - TO_TASK_ID=175
    depends_on:
      rabbitmq-svc:
        condition: service_healthy
    networks:
      - rabbitmq-net

  consumer1-svc:
    container_name: consumer1-ctr
    image: rabbitmq-work-queues-python-consumer:latest
    environment:
      - RABBITMQ_USER=dev_user
      - RABBITMQ_PASSWORD=pa55w0rd
      - MY_CONSUMER_ID=A
    depends_on:
      rabbitmq-svc:
        condition: service_healthy
    networks:
      - rabbitmq-net
  
  consumer2-svc:
    container_name: consumer2-ctr
    image: rabbitmq-work-queues-python-consumer:latest
    environment:
      - RABBITMQ_USER=dev_user
      - RABBITMQ_PASSWORD=pa55w0rd
      - MY_CONSUMER_ID=B
    depends_on:
      rabbitmq-svc:
        condition: service_healthy
    networks:
      - rabbitmq-net


networks:
  rabbitmq-net:
    driver: bridge